# Generated by Django 5.2 on 2025-08-25 08:49

import ckeditor_uploader.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('url', models.URLField(max_length=500, verbose_name='Ссылка')),
                ('icon_class', models.CharField(blank=True, default='', max_length=100, verbose_name='CSS класс иконки')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Отображать')),
            ],
            options={
                'verbose_name': 'ссылку для страницы контактов',
                'verbose_name_plural': 'Ссылки для страницы контактов',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('url', models.CharField(max_length=500)),
                ('title_image', models.ImageField(upload_to='posts/')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField()),
                ('short_text', models.TextField()),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='content')),
                ('is_published', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('Информация', 'Информация'), ('DIY', 'DIY')], max_length=100)),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'пост',
                'verbose_name_plural': 'Посты',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('url', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='products/main/', verbose_name='Главное изображение')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('short_text', models.TextField()),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='description')),
                ('is_published', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('Педали эффектов', 'Педали эффектов')], max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('available', models.BooleanField(default=True)),
                ('vk_url', models.URLField(blank=True, default='', max_length=500, verbose_name='VK ссылка')),
                ('telegram_url', models.URLField(blank=True, default='', max_length=500, verbose_name='Telegram ссылка')),
            ],
            options={
                'verbose_name': 'информацию о продукции',
                'verbose_name_plural': 'Информация о продукции',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_subscribed', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'подписчика',
                'verbose_name_plural': 'Подписчики',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/')),
                ('order', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.productinfo')),
            ],
            options={
                'verbose_name': 'Изображение продукта',
                'verbose_name_plural': 'Изображения продуктов',
                'ordering': ['order'],
            },
        ),
    ]
