# Generated by Django 3.0.5 on 2025-03-13 08:37

import ckeditor_uploader.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('url', models.CharField(max_length=500)),
                ('title_image', models.ImageField(upload_to='title_images')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField()),
                ('short_text', models.TextField()),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='contents')),
                ('is_published', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('Проекты', 'Проекты'), ('IT', 'IT'), ('Мастерская', 'Мастерская'), ('Путешествия', 'Путешествия'), ('Java Base', 'Java Base')], max_length=15)),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_subscribed', models.BooleanField(default=True)),
            ],
        ),
    ]
