# Generated by Django 3.0.5 on 2025-04-21 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20250313_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Информация', 'Информация'), ('DIY', 'DIY'), ('Гитарные педали эффектов', 'Гитарные педали эффектов')], max_length=100),
        ),
    ]
