# Generated by Django 3.0.5 on 2025-04-21 14:14

import ckeditor_uploader.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20250421_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('url', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='products/')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField()),
                ('short_text', models.TextField()),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='contents')),
                ('is_published', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('Гитарные педали эффектов', 'Гитарные педали эффектов')], max_length=100)),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Информация', 'Информация'), ('DIY', 'DIY')], max_length=100),
        ),
    ]
