# Generated by Django 3.0.5 on 2025-04-25 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20250421_1719'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='ProductInfo',
        ),
    ]
