# Generated by Django 3.0.5 on 2025-04-25 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20250425_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinfo',
            name='category',
            field=models.CharField(choices=[('Педали эффектов', 'Педали эффектов')], max_length=100),
        ),
    ]
