# Generated by Django 5.2 on 2025-04-25 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20250425_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinfo',
            name='update_date',
        ),
    ]
