# Generated by Django 5.2 on 2025-08-25 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_productinfo_image_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinfo',
            name='telegram_url',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='Telegram ссылка'),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='vk_url',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='VK ссылка'),
        ),
    ]
