# Generated by Django 5.2 on 2025-08-25 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_productinfo_telegram_url_productinfo_vk_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('url', models.URLField(max_length=500, verbose_name='Ссылка')),
                ('icon_class', models.CharField(blank=True, default='', max_length=100, verbose_name='CSS класс иконки')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Отображать')),
            ],
            options={
                'verbose_name': 'Контактная ссылка',
                'verbose_name_plural': 'Контактные ссылки',
                'ordering': ['order', 'id'],
            },
        ),
    ]
